### ISSUE TITLE
Use a new Shard1 RPC endpoint and report its performance and any issues encountered

### ISSUE THREAD

**Issue by victaphu** [harmony-one/bounties#117]
# Description
A new elastic RPC for Shard1 is now available to be used at https://api.s1.t.hmny.io. We are looking for sanity and stress-testing of the new RPC endpoint.

## Context
The endpoint should function the same as the Shard0 RPC and have the same set of APIs exposed(https://docs.harmony.one/home/developers/api). We are looking for comprehensive testing that will include:
1) regular tx, smart contract deployment
2) all rpc api querying, data verification
3) stress test on all rpc end point

Note: add a new network to connect to shard1:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/44614771/166113623-7118ce29-ebed-4050-aee6-1cfb6718aa26.png">

The stress test will be divided into contract loading, writing operations, and reading operations.

**Contract loading:** we will start by deploying a smart contract onto the blockchain to be used for future operations.

**Writing operations:** the test goal is to confirm that the endpoints are working (sanity test), hence this is where we will run all the write operations, basically any operation that changes the state of the blockchain, (such as transactions or specific contract calls).

**Reading operations**: this step serves as both stress and sanity test. Firstly, we want to determine the scalability of our API(stress test). Secondly we want to run tests across all our endpoints to confirm that they are working as intended (sanity test), trying with different payloads. Please bear in mind this step can and will be run in parallel by creating multiple instances running at the same time.

![image](https://user-images.githubusercontent.com/8563843/171129762-4bf87bbe-f874-4e33-9beb-d707672842d4.png)

Notice that each step shall be dependant on the previous ones. For example, you might need to pass the contract address to the writing and reading steps, feel free to pipe any arguments needed.

All the RPC endpoints that can be found at (https://docs.harmony.one/home/developers/api/methods).

# Acceptance Criteria
Note: as there are not many dApps deployed onto Shard1, bounty hunters should deploy their own smart contracts and run tests against the deployed contract. As such we would like to have a public Github repo that includes the test script and smart contracts  deployed.

Note: we would like the set of test to resemble the usage of a real dApp so we can build a more realistic tests.

We are looking for two testers that can work together on this.

* [x] A Github repository containing the sample smart contract and the test scripts used to deploy and execute the set of tests. The Github Repository should contain a README that describes how to deploy and run the tests.
* [x] A Test Report showing the various endpoints tested and whether they pass/fail the tests run for each RPC endpoint. The test report should also contain statistics on each RPC endpoint (including call duration). These tests will include coverage tests and stress testing scenarios.

# Reward
USD $1000 per tester, up to 2 testers.

**Comment by LeoHChen** [comment]
This bounty is approved for 10 testers with $100 ONE token each.

@diego1q2w and @victaphu please administer this bounty.

**Comment by percybolmer** [comment]
Any takers on this yet, or can I offer my services to start testing this?

**Comment by victaphu** [comment]
> Any takers on this yet, or can I offer my services to start testing this?
Hi @percybolmer 

Yup you can pick this up that would be great! Do you have enough info to start?

**Comment by percybolmer** [comment]
I do belive so, any preference on the tools used during testing I should take into consideration or is it free to use what I want? 

Etc, JavaScript SDK vs Go sdk.

**Comment by victaphu** [comment]
Free to use any tool as long as we can script it and it conforms with the acceptance criteria. We're planning to automate the testing and run tests at scale

**Comment by percybolmer** [comment]
Great, I'll setup a repo tonight and start working on a deploying a smart contract.

Just want to double check, is it 1000 USD ONE per tester or is it 100 USD one Per tester?

**Comment by victaphu** [comment]
Its set to 1000 USD per tester for a max of two testers

**Comment by percybolmer** [comment]
https://github.com/percybolmer/rpc-shard-testing/tree/feature/setupenv

Set up a Repository with some basic stuff for now.

The plan is to use Ganache+Truffle to test on the Localnet and setup smart contracts resembling a real dApp.
Once localnet tests are done it should be easy to switch to the MainNet (witch I changed to the new Shard)

Just need to figure out why Harmony Ganache gives my accounts 0 ONE!

**Comment by percybolmer** [comment]
Figured out the Ganache funding problem. 

Now we can setup the project with a localnet and ganache easily.

To make testing easier I started a Unit test suite using Go. 

Would the following testing tool for the RPC API endpoints be sufficient?
https://github.com/percybolmer/rpc-shard-testing/blob/feature/account_rpc_methods/rpctester/harmony_test.go

Mainly thinking about the results output, or if there is more wanted data in it. 

If thats OK I can go on with starting to implement the other RPC Endpoints, and a sample Contract to deploy and use. 

main repo: https://github.com/percybolmer/rpc-shard-testing

Current branch:feature/account_rpc_methods

1. (Load script is done using Truffle) 
2. Read / Write scripts to be done using go tests, this allows us to also make use of benchmarking and Stress testing easily. 
Also we can control order of flow, etc, make Writes first for instance.

**Comment by percybolmer** [comment]
I have two tracks atm, I am having a hard time deciding on what path to take.

1. Using go unit tests for each RPC endpoint, adding contracts here.
      Usage is basically: ```go test --address="your adr" --url="networkurl"```
      Which outputs a report.json that looks like the following 
      
      ```json
      [
    {
        "method": "hmyv2_getBalanceByBlockNumber",
        "test": "genesis_addr_initial_balance",
        "pass": true,
        "duration": "943.677µs"
    },
    {
        "method": "hmyv2_getBalanceByBlockNumber",
        "test": "missing block",
        "pass": true,
        "duration": "242.109µs"
    },
    {
        "method": "hmy_getBalanceByBlockNumber",
        "test": "addr_initial_balance",
        "pass": true,
        "duration": "269.17µs"
    },
    {
        "method": "hmy_getBalanceByBlockNumber",
        "test": "missing block",
        "pass": true,
        "duration": "265.793µs"
    }
]
      
      ```
2. Using Truffle tests (easiest solution according to me)

Usage: truffle test --network localnet
Outputs a stdout report 

```bash
  Contract: account_methods_v2
    - hmyv2_getBalance: 1 ms
    ✔ getBalance_v2 no Address Param
    - hmyv2_getBalance: 1 ms
    ✔ getBalance_v2
    - hmyv2_getBalance: 1 ms
    ✔ getBalanceByBlock_v2

```

The negative part about truffle test is the output basically.
It is easier to customize output using Go for printing a report.

But if the truffle test output is good enough as output then I'd like to proceed with that. 

You can review the solutions in the repository, would be great if you could just make the decision for me :) 
I personally would probably prefer the Truffle tests as it reduces complexity and keeps it uniformed with ganache+truffle setup. 


https://github.com/percybolmer/rpc-shard-testing/tree/feature/account_rpc_methods

**Comment by diego1q2w** [comment]
Hey @percybolmer!

Both solutions look great. If we get the option to choose we would prefer the Go path since most of the team is proficient with it, also that will give us more flexibility for more granular updates in the future, the output being one of them.

However, if the complexity is exponentially larger then feel free to stick with truffle as long as it fits the criteria.

**Comment by percybolmer** [comment]
Thanks for the response diego, ive removed truffle from the repo and using only go now with ganache since its your preferred path.

Thanks for the input.

I am working on the sanity checks of the RPC methods atm (Slowly atm, been sick this week) But its comming along. 

Just a question, https://docs.harmony.one/home/developers/api/methods/account-methods/getexploreraddress

The address is not a regular endpoint method, but a simple GET, or am I missing something here?

**Comment by percybolmer** [comment]
curl -H "Content-Type:application/json" -X GET "https://api.s1.t.hmny.io/address?id=0xB8260A7255A144a3Aea9b4f9ADB429f76BDC0251&tx_view=ALL&offset=5&page=2"

Actually, the Address call does not seem to work at all for either api.s0 and api.s1,  Either the docs are outdated or something wrong?

**Comment by diego1q2w** [comment]
Thanks @percybolmer and wish you a speedy recovery.

That seems to be part of the explorer service, you can skip that method for now. Let me confirm with the team that's the case.

**Comment by percybolmer** [comment]
https://github.com/percybolmer/rpc-shard-testing

Done with all the Transaction stuff and sanity checking them.
Moving onto Contracts and the rest of the Endpoints 
Will probably be fast to implement those. 

Anyways, Having a hard time figureing out how to perform a Staking Transaction
https://github.com/harmony-one/harmony/blob/24b093b752091fac59c6a4da32950cce04991094/staking/types/transaction.go#L81

I have digged up this that I think I can use, and use 

```	directiveNames = map[Directive]string{
		DirectiveCreateValidator: "CreateValidator",
		DirectiveEditValidator:   "EditValidator",
		DirectiveDelegate:        "Delegate",
		DirectiveUndelegate:      "Undelegate",
		DirectiveCollectRewards:  "CollectRewards",
	}
	``` 
	
	Any of those messages as Directive, but not sure what the Data should be.. 
	
	Any tips for where I can find an Easy sample of how to send a StakingTX?

**Comment by percybolmer** [comment]
Sanity tests and Duration calls for all endpoints mentioned in the DOCS are complete.
Some tests fails, because it does not match data types specified in the DOCS, 
Some other tests fails because the RPC methods does not exists. 
Often the docs says its a number, but returned type might be a string etc. 
I can change that easily if wanted, But i Left it so that you guys can find missmatches easily. 

It is all written to a Report, with data about the call and the params used. 

Only got to fix the Staking transaction, I think I know how to now. 
After that is fixed I need to use the data from the transaction to view the Log endpoints on the Staketransaction.

After that I consider the Sanity test to be completed.

Next Task is Stress Testing.
Can I Claim Both bounties if I proceed to fix the Stress Testing using benchmarks?
(I.e If no other developer comes aboard, can I perform all the tasks solo and claim 2k instead of 1k?)

**Comment by percybolmer** [comment]
@diego1q2w @victaphu , sorry to disturbe, I know times are harsh atm and you are probably swarmed.

Can I get a confirmation that Bounty is still active before proceeding to finish the task? 
Talked to Soph on discord who thought so, If I started before the whole incident, which I did.

Would just be nice with a little "keep going"

**Comment by diego1q2w** [comment]
Sorry @percybolmer, we've been a bit busy. But, don't worry the 2k were previously allocated for this bounty independently the current situation. So to sum up, yes the bounty is still active and yes you can claim the 2k as long as it fits the criteria :)

You are doing a fenomenal job, keep going.

**Comment by victaphu** [comment]
Agreed @percybolmer you're doing great and really appreciate the effort

Keep it up!

**Comment by percybolmer** [comment]
Thanks for Confirming guys! Ill keep going then. 

Just a question, 

For the Staking Transaction Endpoint, I have a problem with how to manage this...
Either I initiate a Staking transaction By delegation ONE to a known Validator, 

This would cost some ONE though. 
Dont know if you guys know any good alternative solution for this.

**Comment by victaphu** [comment]
@diego1q2w any idea?

I think there is ONE faucet but the issue is that you need minimum for delegating
Maybe we can set it up without testing and we can do the testing on our side?

**Comment by diego1q2w** [comment]
@percybolmer for staking, that will be done only for testnet so that's ok, for now pick any testnet validator.

**Comment by percybolmer** [comment]
Thanks! 

All sanity stuff is basically done.
Depending on the network used the results differ ALOT.

There seems to be many differences on the returned data types on the diffrent RPCs. 
But I guess thats why the tool might be needed :D 

Began on the stress testing.

https://github.com/percybolmer/rpc-shard-testing/tree/feautre/stress-test

You can confiugre how many requests to send each endpoint, and how many concurrent requests to increase / decrease stressing.


Transcations to smart contrat might cost a few gas if you send a few htousand requets

**Comment by percybolmer** [comment]
Hey @diego1q2w  and @victaphu.

Just pushed and finalized the Stress testing.
https://github.com/percybolmer/rpc-shard-testing
Master branch has the latest.

The software now supports the following

1. Santiy checking all endpoints by performing transactions, sometimes multiple to verify errors, very easy to add more test cases to each endpoint since I leverage Table driven tests.

You can trigger a santiy check by performing the following command. 
Note that you need to setup the Env variables in .env files, it is all documented in the Readme.
```bash
go test 
```
The endpoints are checked based on the specifications on 
https://docs.harmony.one/home/developers/api

A report will be generated named `results.json` which contains what method passed and which failed, and also params used and the errors that occured. 

Most often this is due that the Docs states a Number return etc, but actually an Hash string is returned etc. 

Errors occured also differs depending on what network you use. Ive tested testnet and devnet for transactions, but also the new shard.


2. Stresstesting / Benchmarking endpoints is possible using the `stress` command.
This command will go through all the endpoints and send X amount of requests, and you can change how many Y requests to send concurrently with flags.

The fuzzer will send all requests (Warning, It does perform Transactions of 0.01 ONE to the Configured Address back and forth, so GAS might stack up if you perform etc 1million transactions)

Results are outputted to a `stress-result.json` 

```json
{
    "addressUsed": "0xfc61332CC9CdFDfCba598131595C96F8C33CE209",
    "network": "https://api.s0.ps.hmny.io/",
    "Methods": {
        "hmy_blockNumber": {
            "Average": "585.761232ms",
            "Responses": 10,
            "Failures": 0
        },
    }
```

Would love it if you guys took a look. 
Until then, I will consider the Bounty completed, unless you guys have any feedback.

Let me know, and we can move on to the fun part, Payday!

**Comment by diego1q2w** [comment]
Thanks @percybolmer, sure thing. We will run a couple of test and then we can move to the good stuff (Payday). If anything we will post any questions here.

**Comment by percybolmer** [comment]
Sure! Hope it's to your liking!

**Comment by diego1q2w** [comment]
@percybolmer thanks for your time and work the tool works as expected. 
Please fill [this form]( https://harmony.one/invoices-one) with 2000 USD.
for "**_Link to your public timesheet - must use Github or Notion_**" field link this bounty
for "**_Who from the core team approved your work_**" field type **_Leo Chen_**

Usually those forms are paid on Fridays but if there is a high throughput of requests it might take a little longer.

**Comment by percybolmer** [comment]
Thanks Diego for your swift handling and swift response to all my previous questions.

This has been a super pleasant experience, I will for sure be on the lookout for more Harmony Bounties.

**Comment by percybolmer** [comment]
Sorry to disturb again, guess there was a delay. No worries,

Forgot to ask, I provided my eth addr, Are the funds received on ETH side or ONE Side? 
Considering the current depeg id very much prefer ETH side of things :)

**Comment by victaphu** [comment]
If you've submitted it should be paid out in USDC on ETH (there will be an option)

Let me follow up, what's your public key if you don't mind sharing, or you can ping me in discord (look for victa in the harmony discord)

**Comment by percybolmer** [comment]
Thanks Victa! No worries though, they where recieved just fine today ! 

Thanks a ton for a great Bounty, hope to see more in the future

**Comment by victaphu** [comment]
Awesome and thank you for the great work

@diego1q2w please confirm if we can close this thanks!

**Comment by diego1q2w** [comment]
Yes @victaphu we can close it and thanks again @percybolmer

**Comment by victaphu** [comment]
Closing Ticket! Thanks @diego1q2w @percybolmer
